; PlatformIO Project Configuration File for test_DMA
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200
build_flags = 
	-D CORE_DEBUG_LEVEL=3
	-I src
